### ISSUE TITLE
Morserino 7.0.1: Keyer broken

### ISSUE THREAD

**Issue by ituri** [oe1wkl/Morserino-32#131]
I have been on the 6.0.0 firmware for quite some time and just updated to 7.0.1. Unfortunately, this broke the CW keyer for me. Once I press my paddle (no matter if it's the left or right one), the keyer registers an increasing amount of paddle presses. Here's a video of that behaviour:

https://www.youtube.com/watch?v=UfMiNnayX44

I have configured iambic B mode and erased my Morserino before flashing the latest firmware.

**Comment by Tomsk666** [comment]
I also have the same issue. upgraded from 6 to 7 and now the keyer just keys on its own after touching a paddle, also the display flashes with every key, just like the video from the other op.
Also, when chrarging (I do have it switched on), the orange light is no longer on, even though it is not fully charged.
I also tried deleteing all user files before upgrading, but same issue. I'll revert back FW and see if that fixes it.

**Comment by oe1wkl** [comment]
2 questions:
1: which device do you have (look at the board version or the loudspeaker: Board V3 with speaker having a metal screen: 1st generation; Board V4 with black loudspeaker: 2nd generation.
2: What is your power supply situation: USB plugged in, y/n? battery switched on y/n? If on battery only, what is the voltage (measured; not what is displayed on the Morserino)?

**Comment by Tomsk666** [comment]
Mine is the M32 version 2, board version rev. 4.1
I tried with the USB plugged in (battery on & off) as well as the battery only (disconnected from USB). Also rebooted as well and same problem. The battery was showing 3.3V on the M32 but the actual battery is 4.1V when tested, as I re-calibrated when I went back to 6.0
I think the firmware update just cleared my battery calibration. All works fine back on verions 6 which I used the command line tool to revert to, as from the flash web page, it gives a 404 not found for the previous version if I try to update through that.

**Comment by ituri** [comment]
Mine is the second version. The issues with the keyer appear regardless of the power supply, both when supplying power via the battery as well as when using USB.

**Comment by oe1wkl** [comment]
I think this was a problem created by platform.io, it did not do a full clean when building the binary. You can try a new software update, and hopefully the problem has disappeared. certainly the problems I saw with WiFi have been resolved by the new build.

**Comment by Lilster** [comment]
Not sure if any of this helps, but I experienced the keyer issue after updating to 7.0. On the first tap, the keyer continued sending dah-dit-dah-dit, etc. I tried reflashing with the “delete everything” option selected, but the issue persisted. I rebooted a few times and nothing changed. I tested on both battery and external power, and the screen dimming with each beep made me wonder if it was some kind of power issue.

I left the device charging for a few hours, came back, and now it works fine. There is still a slight dimming in the header bar when it beeps, but it’s much less noticeable than before.

For reference, the last thing I tried before leaving it to charge was using the touch-sensitive paddles. The issue also happened with the touch paddles, but I only mention it in case it’s relevant. I also had problems with screen alignment and strange characters while the keyer issue was occurring, but again, after charging, I can’t reproduce the issue at all. Everything is now working normally.

Hardware: v2 Rev 4.1, black speaker AST-03208MR-R

Happy to do any testing, re-flashing, etc. if I can help with diagnosis. Regards, Steve
